本次翻译InvalidPluginException和Plugin中的信息
BukkitAPI-Translation-Group/Chinese_BukkitAPI pull request #13
Opened 2018-07-01 04:03 UTC by MineYuanlu

均位于org.bukkit.plugin

2018-07-01 05:29 UTC, XiaoHuiHui233 reviewed
暂且发现这些问题XD

2018-07-01 05:29 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/entity/Arrow.java
> + * 表示箭矢.
我倾向于强调一下an 一支箭矢

2018-07-01 05:29 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/entity/Arrow.java
> +     * 获取箭头的击退强度,这是射箭的{@link org.bukkit.enchantments.Enchantment#KNOCKBACK 力量}等级.
获取箭头的击退等级, 这表示附魔{@link org.bukkit.enchantments.Enchantment#KNOCKBACK 击退}的等级

2018-07-01 05:29 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/entity/Arrow.java
> -     * @return the knockback strength value
附魔击退等级 下同

2018-07-01 05:29 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/entity/Arrow.java
> +     * 重要的箭通常发生在玩家在射箭前拉满弓.
获取此箭矢是否产生暴击.</br>
产生暴击的箭矢会产生更多的伤害并伴随粒子效果.</br>
暴击箭矢通常发生在玩家满弓射箭时.

2018-07-01 05:29 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/entity/Arrow.java
> +     * @return 如果是重要的就返回true
如果是暴击箭矢则返回true

2018-07-01 05:29 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/entity/Arrow.java
> +     * @return 此箭头的拾取状态
那个 箭头箭矢用一个 别一会儿这个一会儿那个
我建议用箭矢

2018-07-01 05:29 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/entity/Arrow.java
> +     * 设置这个箭矢是否应该是重要的.
是否产生了暴击 下同

2018-07-01 06:27 UTC, XiaoHuiHui233 reviewed
问题真的很大

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/InvalidPluginException.java
> + * 当试图加载无效插件文件时抛出异常.
我觉得把 抛出异常 改为 抛出此异常 会更好一些

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/InvalidPluginException.java
> +	 * 用指定的详细消息和原因构造一个新的 InvalidPluginException.
用给定的详细信息和导致异常的原因构造一个新的InvalidPluginException. 详细消息改为详细信息 原因强调导致异常的原因 下同

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> + * 对于实际实现,建议使用 {@link PluginBase}.
表示一个插件
我发现你好像都不喜欢翻译冠词 面向对象的编程 一个对象就是表示某个事物的一个实体 强调一个很重要
除非它是工具类 或者单例类
这只是一个接口, 如果想要一个实际的实现, 建议使用{@link PluginBase}.

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +     * 返回插件数据文件所在的文件夹. 文件夹可能尚未存在.
返回插件的数据文件夹, 该文件夹可能尚未创建.

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +     * 返回包含该插件详细信息的plugin.yaml文件.
返回封装有该插件plugin.yaml文件中详细信息的实例.

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +     * 如果在这个插件中嵌入了默认的config.yml,它将作为这个配置的默认设置.
获取这个插件的{@link FileConfiguration}实例, 它将读取config.yml中的内容.
如果这个插件中含有config.yml文件, 那么这个config.yml将作为默认的配置文件.

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +     * 获取此插件中的嵌入资源
获取此插件包中的资源

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +     * 保存{@link FileConfiguration},可通过{@link #getConfig()}检索.
保存插件的 {@link FileConfiguration}, 这可以使用{@link #getConfig()}获取.

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +	 * 如果config.yml已经存在，这将是必然失败.
将默认的config.yml文件数据保存到{@link #getConfig()}获取的config.yml所在的位置.<br>
这不会覆盖已经存在的config.yml.

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +	 * 使用与.jar文件相同的层次结构将资源保存到插件的数据文件夹中(保存子目录).
用插件的.jar文件保存某个资源的原始内容, 并确保可以使用{@link #getResource(String)}找到.<br>
这将使用与.jar文件相同的层次结构将资源保存到插件的数据文件夹中(同时保存子目录).

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +	 * @throws IllegalArgumentException 如果资源路径为null/空,或指向不存在的资源
最后加一句则抛出 更好一点XD

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +     * 返回一个布尔值,该值指示当前是否启用此插件
返回一个布尔值,表示该插件此时是否已经启动.

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +     * @return 如果启用此插件,则为true，否则为false.
如果此插件已经启动,则为true，否则为false.

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +     * 当加载多个插件时,在调用任何onEnable()之前调用所有插件的onLoad().
在一个插件被加载之后启动之前调用.<br>
当有多个插件加载时,确保所有插件的onLoad()全部调用完毕后才会调用onEnable().

2018-07-01 06:27 UTC, XiaoHuiHui233 commented on BukkitApi/org/bukkit/plugin/Plugin.java
> +     * 这应该返回插件的裸名,并且应该用于比较.
人家叫 无修饰名称 哪里来的 裸名

2018-07-01 10:04 UTC, hcrgm requested changes

2018-07-01 10:04 UTC, hcrgm commented on BukkitApi/org/bukkit/entity/Horse.java
> +     * @deprecated 看 {@link ChestedHorse}
"see"应该翻译为“请参阅”，更合适

2018-07-01 14:13 UTC, andylizi commented on BukkitApi/org/bukkit/entity/Arrow.java
> + * 表示一只箭矢.
箭的量词是支。

2018-07-18 04:13 UTC, hcrgm approved these changes

2018-07-18 04:14 UTC, merged