对 Plugin 和 PluginManager
BukkitAPI-Translation-Group/Chinese_BukkitAPI pull request #19
Opened 2018-12-04 11:32 UTC by LamGC

对以下类进行部分翻译：
org/bukkit/plugin/Plugin.java
org/bukkit/plugin/PluginManager.java

目前存在的问题:
[org/bukkit/plugin/Plugin.java:160]               getLogger()的详细说明可能有歧义，这里不太清楚怎么说会较好理解。
[org/bukkit/plugin/Plugin.java:173]               getName()的详细说明有个"bare name"不是很懂官方文档的意思。
[org/bukkit/plugin/PluginManager.java:316] getPermissions() 的返回值,说是"Set对象"比较好还是"集合对象"比较好。

最近不是很常上github，但是都会看看的，所以有问题的话修复会要一些时间，见谅QAQ

2018-12-04 11:33 UTC, LamGC commented
（另外说一下，Commit 1521074 和 888570a 是上次帮忙翻译的Commit，不知道为什么突然也加入到这个Pull Request了...QAQ）

2018-12-04 11:41 UTC, LamGC commented
冲突解决了
- 上次翻译的内容保持不变
- [org/bukkit/plugin/Plugin.java:173] 已有觉得合适的翻译，删除本人翻译内容
- [org/bukkit/plugin/Plugin.java:160] 详细说明有合适的翻译，删除本人翻译内容
- ...(原谅我忘记了还解决了什么冲突- -)

2018-12-04 18:02 UTC, andylizi requested changes
这个项目的文件换行符是 Windows 的 `CRLF` 而不是 Linux 的 `LF`。

2018-12-05 02:08 UTC, LamGC commented
emmmmmm我看了一下确实是CRLF换行符而不是LF换行符，Git的AutoCRLF的问题吗？....

2018-12-05 04:12 UTC, andylizi commented
很可能。看 diff 就会发现整个文件都被更改了。

---

> （另外说一下，Commit [1521074](https://github.com/BukkitAPI-Translation-Group/Chinese_BukkitAPI/commit/15210748d624e02703d39c56911e6788ee5e6554) 和 [888570a](https://github.com/BukkitAPI-Translation-Group/Chinese_BukkitAPI/commit/888570a93515f499a13ad065fd428536210c5367) 是上次帮忙翻译的Commit，不知道为什么突然也加入到这个Pull Request了...QAQ）

你可以用 force push。

2018-12-05 06:42 UTC, LamGC commented
我打算把fork出来的仓库全部更新一遍再进行翻译，距离上次翻译太久了，仓库都没更新-w-，这个Pull Request我先关了

2018-12-05 06:42 UTC, closed without merging