翻译PluginManager部分Javadoc
BukkitAPI-Translation-Group/Chinese_BukkitAPI pull request #4
Opened 2017-09-28 12:19 UTC by LamGC

比较简单的部分已经翻译，可能有点错误。

2017-09-28 14:20 UTC, andylizi requested changes

2017-09-28 14:20 UTC, andylizi commented on BukkitApi/org/bukkit/plugin/PluginManager.java
> +     * 获取已成功载入的插件对象.
`a list of`，`currently`
> 获取所有当前已载入的插件。

`loaded` 只能表示已被 bukkit 载入（`onLoad()` 触发），”已成功载入“ 的说法会让用户以为指的是被启用（enabled）的插件

2017-09-28 14:20 UTC, andylizi commented on BukkitApi/org/bukkit/plugin/PluginManager.java
> +     * 获取默认权限或op所拥有的权限
结尾需要英文句号。

2017-09-28 14:20 UTC, andylizi commented on BukkitApi/org/bukkit/plugin/PluginManager.java
>      public Set<Permission> getDefaultPermissions(boolean op);
这里感觉有点绕口了，但一时半会想不出应该翻译成什么更好…
还有就是，不是“OP状态下的权限”和”OP所拥有的权限“，而是“OP状态下默认拥有的权限”和”OP默认拥有的权限“。

2017-09-28 14:20 UTC, andylizi commented on BukkitApi/org/bukkit/plugin/PluginManager.java
> +     * 停用并删除所有插件.
可能造成歧义，让用户以为是真的会“删除”插件…
建议翻译为 ”停用所有插件，并清空已注册的插件列表“ 一类的。（仅供参考）

2017-09-29 10:30 UTC, LamGC commented on BukkitApi/org/bukkit/plugin/PluginManager.java
>      public Set<Permission> getDefaultPermissions(boolean op);
好的，我修改一下

2017-09-29 10:31 UTC, LamGC commented on BukkitApi/org/bukkit/plugin/PluginManager.java
> +     * 获取已成功载入的插件对象.
这里改一下加个注明吧...

2017-09-29 10:35 UTC, andylizi commented on BukkitApi/org/bukkit/plugin/PluginManager.java
> +     * 获取已成功载入的插件对象.
其实只要加入 ”所有“ 并移除 ”成功“ 就好了。

2017-09-29 10:55 UTC, LamGC reviewed
已对提出意见做出修改 -170929

2017-09-29 10:55 UTC, LamGC commented on BukkitApi/org/bukkit/plugin/PluginManager.java
> +     * 停用并删除所有插件.
emmmmmm，这个测试了一下，只会停用已启用的插件并从PluginManager删除插件对象

2017-09-29 11:22 UTC, andylizi commented on BukkitApi/org/bukkit/plugin/PluginManager.java
> +     * 停用并删除所有插件.
是的啊。但是“删除”可能会让用户误解为是删除 jar 文件…因为删除这个词一般对应的是 delete，当需要表达“从列表中移除某一项“时用的是移除，对应 remove。

2017-09-29 11:24 UTC, merged

2017-09-29 11:24 UTC, andylizi commented
感谢~

2017-10-02 08:19 UTC, hcrgm commented
+1~

2017-12-13 14:45 UTC, MikuPy2001 commented on BukkitApi/org/bukkit/plugin/PluginManager.java
> +     * 停用并删除所有插件.
停用并移除所有插件?